### ISSUE TITLE
Adding chatbot to multiple rooms?

### ISSUE THREAD

**Issue by ridoy** [robkorn/urbit-chatbot-framework#4]
Context:
- We're building a financial data chatbot described by this grant: https://urbit.org/grants/cypherscope-bot
- You can add it to your chat and query it for financial charts, like BTCUSD prices for the last week.
- We expect this to be added to multiple chats and expect it to run on a single Moon
- The bot is currently stateless BUT we expect to have a paid tier so we may need to store a mapping of chats to payment tier.

Issue:
Our bot's `fn main()` consists of the constructor:
`Chatbot::new_with_local_config(respond_to_message, "~mitten-dapper", "chat-3973").run();`

I guess I'm looking for the best way to implement this stuff:
1) Listen for when we're added to a new chat (and spawn a new chatbot)
2) Persist which chats contain our chatbot as a member, so nothing is lost if the Moon shuts down

I couldn't find anything resembling this in the examples.

Thank you!

**Comment by robkorn** [comment]
Ah, great to see interest in using this framework for an interesting grant.

For your requirements I'd recommend subscribing to graph-store or hark-store for tracking when you're added to a new chat, and having a local data store (file or database) which you save the chat info to locally. Then on reboot, create a new chatbot struct for each of the locally saved chats.

**Comment by ridoy** [comment]
Thanks!. Will get back to you shortly if I have more questions.
